# Generated by Django 2.2.8 on 2020-01-26 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTypesClubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва типу гуртка')),
            ],
            options={
                'verbose_name': 'Тип діяльності гуртків',
                'verbose_name_plural': 'Типи діяльності гуртків',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Назва кантакту')),
                ('content', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зміст контакту')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакти',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='ContentTypesLegals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва типу документа')),
            ],
            options={
                'verbose_name': 'Тип документів',
                'verbose_name_plural': 'Типи документів',
            },
        ),
        migrations.CreateModel(
            name='ContentTypesNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва типу новини')),
            ],
            options={
                'verbose_name': 'Тип новин',
                'verbose_name_plural': 'Типи новин',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name="Им'я")),
                ('last_name', models.CharField(max_length=40, verbose_name='Прізвище')),
                ('position', models.CharField(max_length=35, verbose_name='Посада')),
                ('characters', models.TextField(max_length=1000, verbose_name='Характеристика')),
                ('photo', models.ImageField(default='default/default_image_employee.png', upload_to='image/employee_image/', verbose_name='Фотокартка')),
            ],
            options={
                'verbose_name': 'Співробітник',
                'verbose_name_plural': 'Співробітники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва події')),
                ('date_placing', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата проходження події')),
                ('detail', models.FileField(default='default/default_detail.pdf', upload_to='detail/event_detail/', verbose_name='Документ з детальною інформацією')),
            ],
            options={
                'verbose_name': 'Подія',
                'verbose_name_plural': 'Події',
                'ordering': ['-date_placing'],
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва організації')),
                ('description', models.TextField(max_length=1000, verbose_name='Короткий опис')),
                ('partner_link', models.URLField(max_length=100, verbose_name='Посилання на сайт партнера')),
                ('logo', models.ImageField(default='default/default_image_partner.png', upload_to='image/partner_image/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнери',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва курсу')),
                ('description', models.TextField(blank=True, help_text='Введіть основну інформацію про курс', max_length=5000, verbose_name='Опис діяльності підготовчого курсу')),
                ('image', models.ImageField(default='default/default_image_training_course.png', upload_to='image/training_course_image/', verbose_name='Емблема або інше характерне зображення')),
                ('detail', models.FileField(default='default/default_detail.pdf', upload_to='detail/training_course_detail/', verbose_name='Документ з детальою інформацією')),
            ],
            options={
                'verbose_name': 'Підготовчий курс',
                'verbose_name_plural': 'Підготовчі курси',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок новини')),
                ('post_date', models.DateField(auto_now_add=True, verbose_name='Дата публікації')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Опис новини')),
                ('image', models.ImageField(default='default/default_image_new.png', upload_to='image/new_image', verbose_name='Основне зображення новини')),
                ('detail', models.FileField(default='default/default_detail.pdf', upload_to='detail/new_detail/', verbose_name='Документ з детальною інформацією')),
                ('visitors_type', models.CharField(choices=[('p', 'Батьки'), ('s', 'Студенти'), ('w', 'Працівники'), ('f', 'Партнери')], default='s', max_length=1, verbose_name='Тип користувача')),
                ('content_types', models.ManyToManyField(default='Загальний', related_name='news', to='public.ContentTypesNews', verbose_name='Типи новини')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Legals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва документа')),
                ('detail', models.FileField(default='default/default_detail.pdf', upload_to='detail/legal_detail/', verbose_name='Документ з детальою інформацією')),
                ('content_type', models.ForeignKey(on_delete=models.SET('Документ'), to='public.ContentTypesLegals', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва гуртка')),
                ('description', models.TextField(blank=True, help_text='Введіть основну інформацію про гурток', max_length=5000, verbose_name='Опис діяльності гуртка')),
                ('image', models.ImageField(default='default/default_image_club.png', upload_to='image/club_image/', verbose_name='Емблема або інше характерне зображення')),
                ('detail', models.FileField(default='default/default_detail.pdf', upload_to='detail/club_detail/', verbose_name='Документ з детальою інформацією')),
                ('season_set', models.CharField(choices=[('a', 'Весь рік'), ('e', 'Академічний рік'), ('s', 'Літні канікули')], max_length=1, verbose_name='Час активності')),
                ('members_age', models.CharField(choices=[('p', 'Учні'), ('s', 'Студенти'), ('c', 'Учні/Студенти')], default='c', max_length=1, verbose_name='Вік відвідувачів гуртка')),
                ('activity_type', models.ForeignKey(on_delete=models.SET('Навчальний'), to='public.ActivityTypesClubs', verbose_name='Напрямок діяльності гуртка')),
            ],
            options={
                'verbose_name': 'Гурток',
                'verbose_name_plural': 'Гуртки',
                'ordering': ['name'],
            },
        ),
    ]
