# Generated by Django 2.2.8 on 2020-03-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20200217_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='detail_hash',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Хеш детальної інформації'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_hash',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Хеш зображення новини'),
        ),
    ]
